const lessonFaq = [
  {
    question: 'What kind of lessons are available?',
    answer:
      'Geleza provides both written and video lessons. While you can easily download written materials and access them offline, watching videos will require an internet connection.',
  },
  {
    question: 'Are lessons available on a free plan?',
    answer:
      'Lessons as well as the ability to talk to teachers on a one-to-one session are currently not available not available on the free plan.',
  },
  {
    question: 'How long is each lesson?',
    answer: 'On average, a video lesson has a duration of 20 - 25 minutes.',
  },
  {
    question:
      'What should I do if what is being taught in not correct or relevant',
    answer:
      'You can instantly reach out to any available teacher if you suspect the lesson being taught is not relevant.',
  },
  {
    question: 'Are all lessons generated by A.I?',
    answer:
      "Geleza's lessons are developed by professional teachers and reviewed by artificial intelligence. While the lesson presenter may be an A.I., the content is always created by qualified tutors.",
  },
]
export default lessonFaq
