const lessonFaq = [
  {
    question: 'What kind of lessons are available?',
    answer:
      'Geleza provides only written lessons. Video lessons will be available in the future.',
  },
  {
    question: 'Are lessons available on a free plan?',
    answer:
      'Lessons as well as the ability to talk to teachers on a one-to-one session are currently not available on the free plan.',
  },
  {
    question: 'How long is each lesson?',
    answer:
      'You choose your own pace and how much you want to learn, there is no fixed length or duration for a course or lesson.',
  },
  {
    question:
      'What should I do if what is being taught in not correct or relevant',
    answer:
      'You can instantly reach out to any available teacher if you suspect the lesson being taught is not relevant.',
  },
  {
    question: 'Are all lessons generated by A.I?',
    answer:
      'You as a student, will have to guide Geleza on what you want to learn. You create your own curriculum and the A.I generate lessons for you.',
  },
]
export default lessonFaq
