const libraryFaq = [
    {
      question: 'What can I read?',
      answer:
        "You can choose either school work, facts, articles, short stories, jokes and more.",
    },
    {
      question: 'How long is the reading time for each content?',
      answer:
        'Generated content under the library takes about 5 - 10 minutes to read, depending on your reading speed.',
    },
    {
      question: 'Can I save my content?',
      answer:
        'Absolutely. We are working on the ability to save your content and read later. You can also copy the content and share with friends.',
    },
    {
      question: 'Are all content generated by A.I?',
      answer:
        'Yes. Everything you will read under the library is generated by the Geleza AI, Zeda, on demand.',
    },
  ]
  export default libraryFaq
  