const preppalFaq = [
  {
    question: 'How are questions generated?',
    answer:
      "PrepPal's test questions are based on a curriculum of a subject or course you are doing, so they are always highly accurate to what you may face in your examinations.",
  },
  {
    question: 'How many questions do I get per test?',
    answer:
      'You can choose any number of questions. It is advisable to choose the number of question you will be able to answer and complete in time.',
  },
  {
    question: 'Can I see my previous test and answers?',
    answer:
      'Absolutely. All your exams preparation tests and answers are saved in real time, and you can access them anytime you want.',
  },
  
  {
    question: 'Are all questions generated by A.I?',
    answer:
      'Yes. All PrepPal questions are generated, moderated and marked by A.I.',
  },
]
export default preppalFaq
